name: Publish

on:
  tags:
    - 'v*'

jobs:
  publish:
    name: Publish
    environment: prod
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Project
        uses: ./.github/actions/setup-project

      - name: Set version
        id: version
        run: echo "ORG_GRADLE_PROJECT_VERSION_NAME=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Publish Library
        run: |
          echo "Publishing and Releasing library 🚀"
          ./gradlew publishToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_VERSION_NAME: ${{ env.ORG_GRADLE_PROJECT_VERSION_NAME }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
              --title "$TAG" \
              --verify-tag
          shell: bash